README.md

* uses description in ruby-doc for now as its better than no description.
https://ruby-doc.org/stdlib-2.3.0/libdoc/webrick/rdoc/WEBrick.html

Add Readme description

---

test/webrick/test_htgroup.rb

Add test for class `WEBRick::HTTPAuth::Htgroup`. A test for this class is missing.

Add missing test for WEBrick::HTTPAuth::Htgroup

---

test/webrick/test_httpproxy.rb

Net::HTTP warns about setting the default content_type when using POST verb:
> Content-Type did not set; using application/x-www-form-urlencoded
Before
After

Silence Net::HTTP warning in test

---

lib/webrick/httputils.rb

I noticed this type missing when I was serving an _Emscripten_ app.

Adds WebAssembly MIME type

---

lib/webrick/httpresponse.rb
test/webrick/test_httpresponse.rb

Remove extraneous spaces after the status code that is
non-compliant with RFC, i.e `HTTP 200 OK `, to unnecessary
confusion for WEBrick users, by a risk that WEBrick instances in
the wild will have server responses flagged as suspicious or
malicious due to a similar bug in [Cobalt Strike
misconfiguration].
Reported by Matt Tennis <mtennis@paloaltonetworks.com>
[Cobalt Strike misconfiguration]: https://blog.fox-it.com/2019/02/26/identifying-cobalt-strike-team-servers-in-the-wild/

Remove extraneous spaces at the end of status line

---

test/webrick/test_httpstatus.rb

Hi,
This PR improves the test coverage of httpstatus.rb from __92.5%__ to __100.0%__.
The coverage at the moment.
https://rubyci.s3.amazonaws.com/debian8-coverage/ruby-trunk/lcov/ruby/lib/webrick/httpstatus.rb.gcov.html
With this PR

Improve httpstatus.rb's test coverage

---

test/lib/envutil.rb
test/webrick/test_filehandler.rb

Hi!
This PR adds `EnvUtil#timeout` to run a test of CI.
This module_function is missing.
- https://travis-ci.org/ruby/webrick/builds/549516037
I used [ruby/ruby](https://github.com/ruby/ruby/blob/master/tool/lib/envutil.rb#L68L73) to add `EnvUtil#timeout` as a reference.
Please comment if it should be solved in other ways.

add EnvUtil#timeout

---

lib/webrick/httpresponse.rb

It is currently broken, and even if it worked, it can cause problems
when debugging.  See https://bugs.ruby-lang.org/issues/10715.
I think this is better than fixing the method, which is the approach
that #20 is taking.

Remove Webrick::HTTPResponse#to_s

---

lib/webrick/httpresponse.rb
test/webrick/test_httpresponse.rb

This is a follow up to d9d4a28f1cdd05a0e8dabb36d747d40bbcc30f16.
The commit prevented CRLR, but did not address an isolated CR or an
isolated LF.
Co-Authored-By: NARUSE, Yui <naruse@airemix.jp>

WEBrick: prevent response splitting and header injection

---

lib/webrick/httpauth/digestauth.rb
test/webrick/test_httpauth.rb

Create the substrings necessary parts only, instead of cutting the
rest of the buffer.  Also removed a useless, probable typo, regexp.

Loop with String#scan without creating substrings

---

lib/webrick/httputils.rb
test/webrick/test_httprequest.rb

While the stripping of header values is required by RFC 2616 4.2 and
RFC 7230 3.2.4, the squishing is not and can break things, such as
when one header contains an HMAC of another header.
Fixes Ruby Bug 7021.

Remove the squishing of whitespace in header values

---

lib/webrick/accesslog.rb

Only untaint result on Ruby <2.7, as taint support is deprecated
in Ruby 2.7+ and no longer has an effect.

Don't check tainting in access log escaping

---

lib/webrick/httpresponse.rb
test/webrick/test_httpresponse.rb

Patch from Leonard Garvey.
Fixes Ruby Bug 9986.

Enabled chunked encoding if Transfer-Encoding: chunked header is set

---

lib/webrick/httpservlet/cgihandler.rb
test/webrick/test_filehandler.rb
test/webrick/utils.rb

This way you don't need to escape each entry.
Implements Ruby Feature 15170.

Allow WEBrick::HTTPServlet::CGIHandler :CGIInterpreter option to be array

---

lib/webrick/httpproxy.rb

The "evil-proxy" gem [1] allows one to create an HTTPS man-in-the-middle proxy using webrick/httpproxy as the base.
It's a fairly unmaintained gem and therefore has fallen behind not-so-recent changes within webrick.
The biggest issue with e-p is its use of perform_proxy_request from webrick/httpproxy. Since httpproxy does not handle HTTPS requests in normal use the Net::HTTP object does not respect the fact that it might be used for that. Therefore evil-proxy basically has a cut/paste version of perform_proxy_request within it. So that means any changes to webrick require another cut-and-paste update to e-p.
I'd like to use e-p but I'd rather not cut-and-paste the method back in. Therefore I'm wondering if the following small patch would be acceptable. It simply moves the Net::HTTP.new …

Extract creation of Net::HTTP in httpproxy

---

test/webrick/test_cgi.rb

JRuby's environment variables are provided by the Java Development
Kit's (JDK's) classes, which present them as a map from string to
string. In order to do this, those environment variable names and
values must be decoded into characters, which breaks any variables
that are intended to be "raw" bytes not necessarily decodable with
the default system encoding.
This issue is detailed in jruby/jruby#6248. The only solution on
the JRuby side will be to bypass the JDK environment variable API
and go directly to the native getenv/setenv system calls. This is
not likely to happen in the near future, due to the complexity of
such a change and the rarity of undecodable environment values.
The exclude here was added due to the Windows platform also having
a similar sensitivity to character …

Skip env-locale-sensitive CGI test on the "java" platform

---

lib/webrick/httprequest.rb

Fixes #43 by unshifting portion of chunk that exceeds requested length.

Make readpartial limit chunk to appropriate size

---

test/webrick/test_filehandler.rb

This syntax is not supported until Ruby 2.5, and Webrick still
targets Ruby 2.3+.

Do not use ensure in a block without begin

---

lib/webrick/httprequest.rb
test/webrick/test_httprequest.rb

RFC 7230 section 3.3.3 allows for this.
Fixes #30

Allow empty POST and PUT requests without content length

---

test/webrick/test_httpproxy.rb

It was added after Ruby 2.5, and it looks like it never ran correctly
on Ruby <2.5.

Only run test_big_bodies test on Ruby 2.5+

---

test/webrick/test_filehandler.rb

This test would fail previously in my environment when US-ASCII
encoding is used:
```
WEBrick::TestFileHandler#test_cjk_in_path:
Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /tmp/__20200715-38642-1ygisw8
```

Fix test when run with US-ASCII encoding

---

lib/webrick/server.rb
test/webrick/test_server.rb

I would like to be able to fork a webrick server and then shut it down from the parent process.
The @shutdown_pipe variable within webrick/server is the perfect tool for the job but it is not settable/accessible outside of the class. This patch simply allows for a pipe to be passed in via the server config.

Allow shutdown_pipe to be passed in via @config

---

test/webrick/test_server.rb

This addresses the test issue from #44. It appears the issue is that the server aborts for an unknown reason. There is no other way the pipe could be closed when the attempt to write to it occurs.
Looking at the test directly above the new one https://github.com/ruby/webrick/blob/1daacc18490cbc96bcf1bdc741f3ccff65a0d164/test/webrick/test_server.rb#L151-L161- it appears that it assumes that a server may not start properly and simply appears to skip the test if the server fails to start. The only way on line 156 that the thread status is a falsy value is if the thread is already dead when it is examined. That would imply the server is non-existent at that point.
The fix tries 10 times to bring up a server and if it fails to do so - it continues on.

Fix shutdown_pipe test issue

---

test/webrick/test_httpserver.rb

MacOS seems to raise this error in some cases.

Allow EPROTOTYPE error when writing junk to a socket

---

test/webrick/test_server.rb

As mentioned in #44 and #54 - there continues to be issues with regards to the server startup with regards to this test. WEBrick::GenericServer#stop swallows an IOError internally - so the fix here is to swallow the error during the test and to retry.

Refix test_shutdown_pipe

---

lib/webrick/httprequest.rb

Some regexps were too tolerant.

Make it more strict to interpret some headers

---

.github/workflows/test.yml
webrick.gemspec

ruby 2.3 now raise an ArgumentError while running tests
```
........E
===============================================================================
Error: test_slow_connect(TestWEBrickSSLServer): ArgumentError: wrong number of arguments (given 3, expected 1..2)
/opt/hostedtoolcache/Ruby/2.3.8/x64/lib/ruby/2.3.0/timeout.rb:73:in `timeout'
/home/runner/work/webrick/webrick/test/lib/envutil.rb:72:in `timeout'
/home/runner/work/webrick/webrick/test/webrick/test_ssl_server.rb:58:in `test_slow_connect'
55:       :SSLEnable => true,
56:       :SSLCertName => "/C=JP/O=www.ruby-lang.org/CN=Ruby",
57:     }
=> 58:     EnvUtil.timeout(10) do
59:       TestWEBrick.start_server(Echo, config) do |server, addr, port, log|
60:         outer = TCPSocket.new(addr, port)
61:         inner = …
```

More rubies on CI, deprecating ruby 2.3 due to test failure

---

lib/webrick/httputils.rb

This PR adds a MIME type for the Web Application Manifest standard.
https://developer.mozilla.org/en-US/docs/Web/Manifest#deploying_a_manifest_with_the_link_tag
https://w3c.github.io/manifest/#media-type-registration

add mime type for .webmanifest extension

---

test/webrick/test_httpproxy.rb
test/webrick/test_https.rb

Server Name Indication does not allow IP addresses (RFC 6066, section 3:
`Literal IPv4 and IPv6 addresses are not permitted in "HostName".`).
Recent versions of LibreSSL enforce this requirement, and the tests
currently break when running on such versions.  Use localhost
instead of 127.0.0.1 to avoid the issue.  This requires adding
HTTPSNITest#connect, because s.hostname= is called before
ssl_socket_connect.

Fix invalid use of IP addresses in SNI

---

webrick.gemspec

I'm currently (trying)[https://github.com/void-linux/void-packages/pull/31003] to package this for void, and have discovered that the `bin/console` and `bin/setup` files are included in the gemspec, and would be installed in the system `/usr/bin` directory when trying to install this package system-wide. My understanding is that these binaries are useful for development on `webrick` only, and should not be packaged, but I'm not familiar with ruby at all and could be wrong here.

remove unneeded bin/console and bin/setup files from gemspec

---

lib/webrick/httpservlet/prochandler.rb
lib/webrick/version.rb
test/webrick/test_httpserver.rb

Addressing issue https://github.com/ruby/webrick/issues/69

Accept put requests

---

lib/webrick/httprequest.rb

Allows for someone to override the parsing to accommodate "alternatives".
One could write the following to allow underscores in host names.
```
require 'webrick/httprequest'
module WEBrick
class HTTPRequest
private
def parse_host_request_line(host)
uri = URI.parse("scheme://#{host}")
[uri.host, uri.port]
end
end
end
```
Also adding the "o" option to the regex so the regex is only built once.``

Move the host request parsing to a separate method.

---

lib/webrick/ssl.rb

This is currently done even in non-$VERBOSE mode.  My guess as to
the reason it is done is to give the user the impression that the
server is doing something and not frozen, but I still think there
should be a way to disable it.  If the $VERBOSE flag isn't a good
way to do that, let's offer some other way to do that.

Only output prime information to $stderr if $VERBOSE

---

lib/webrick/httpresponse.rb
test/webrick/test_httpresponse.rb
test/webrick/test_httpserver.rb

Previously, there was no way to implement connection upgrade or proper streaming. The systems I've checked which attempt to do this end up monkey patching webrick. So, let's make it possible without monkey patching. This is required for Rack 3.
This allows streaming which uses `connection: close` when no content-length is known. It also avoided buffering the entire response which causes problems for streaming real-time responses.

Better support for connection upgrade and bi-directional streaming.

---

lib/webrick/httpresponse.rb
test/webrick/test_httpresponse.rb

This is affecting Rack v2 which appends to the response body:
https://github.com/rack/rack/blob/cd4c9f0e4befccd53c3f03ed9af8c9a9c438d0a9/lib/rack/handler/webrick.rb#L119-L121

Body should be non-frozen by default.

---

lib/webrick/httputils.rb

Introduced in 037e8523a55f2c986b21106ef105517179bf3574 (19 years ago).
The duplicate key of same name was in that file as well.
The value we keep, and have had since introduction, `"crl" => "application/pkix-crl"`, seems to be in harmony with the [RFC 2585](https://www.rfc-editor.org/rfc/rfc2585#section-4.2).
See
https://www.iana.org/assignments/media-types/application/pkix-crl

Drop commented-out line

---

lib/webrick/httprequest.rb
test/webrick/test_httprequest.rb

Addresses CVE-2023-40225.
Fixes #119

Raise HTTPStatus::BadRequest for requests with invalid/duplicate content-length headers

---

test/webrick/test_cgi.rb
test/webrick/test_filehandler.rb
test/webrick/utils.rb

The test is currently skipped and can't possibly work on windows at the moment. It fails because $LOAD_PATH is not set up properly in the forked CGI process, so require 'uri' fails.  This works properly in the test_cgi.rb tests, because it sets up a :RequestCallback to fix things up. Let's move the setup there into util.rb, so it can be shared with test_filehandler.rb as well.

Fix WEBrick::TestFileHandler#test_short_filename test not working on mswin

---

lib/webrick/httprequest.rb
test/webrick/test_httprequest.rb

This fixes a request smuggling vulnerability (Fixes #124).

Fix bug chunk extension detection

---

lib/webrick/httprequest.rb
lib/webrick/httputils.rb
test/webrick/test_httprequest.rb

HTTP/1 specifies user agent MUST only give one `cookie` header. However, in practice, servers should be robust when encountering more than one, merging them, and preserving the semantics.
WEBrick already correctly handles this case, but it fails to correct expose the headers.
See <https://github.com/socketry/rack-conform/pull/19> for more context.

Merge multiple cookie headers, preserving semantic correctness.

---

.github/workflows/test.yml

Followup: https://github.com/ruby/webrick/pull/131
But exclude Ruby 2.4 and 2.5 because they aren't supported on macos-arm64.

Test on macos-latest

---

lib/webrick/httprequest.rb
lib/webrick/httputils.rb
test/webrick/test_filehandler.rb
test/webrick/test_httprequest.rb

Disallow bare CR, LF, NUL in header and request lines. Tighten parsing of request lines to only allow single spaces, as specified in the RFCs.
Forcing this RFC-compliant behavior breaks a lot of tests, so fix the tests to correctly use CRLF instead of LF for requests (other than the specific checks for handling of bad requests).
Fixes #137

Require CRLF line endings in request line and headers

---

lib/webrick/httputils.rb
test/webrick/test_httprequest.rb

Previously, all whitespace was stripped, but that goes against the related RFCs.
Fixes #139

Only strip space and horizontal tab in headers

---

lib/webrick/httprequest.rb
test/webrick/test_httprequest.rb

Fix tests that did not have correctly formatted headers.
Fixes #140

Treat missing CRLF separator after headers as an EOFError

---

lib/webrick/httprequest.rb

Recent changes in the URI gem make it so that this constant may not be there. And I think even with older versions of the gem, it would depend on what the default parser was set to.
cc @jeremyevans

Fix reference to URI::REGEXP::PATTERN::HOST

---

lib/webrick/httprequest.rb
test/webrick/test_httprequest.rb

If a request has both a content-length and transfer-encoding headers, return a 400 response.  This is allowed by RFC 7230 section 3.3.3.3.
Fixes #145

Prevent request smuggling

---

sig/server.rbs

Fix `[error] The method cannot be called without a block`
`Diagnostic ID: Ruby::RequiredBlockMissing` in Usage of README.

Block of server.start is optional

---

lib/webrick/httpauth/authenticator.rb
lib/webrick/httpauth/htgroup.rb
lib/webrick/httpauth/htpasswd.rb
lib/webrick/httprequest.rb
sig/httpauth/authenticator.rbs
sig/httprequest.rbs

This PR improves some codes that I found when I was adding RBS.
* Remove an unused instance variable.
* Fix some typos.
* `req.addr` and `req.peeraddr` initialize `[]` instead of `nil`, so those types can be non-nil.
* `v1, v2 = split(sep)` should be `v1, v2 = split(sep, 2)`.

Fix bugs and improve

---

lib/webrick/cgi.rb
lib/webrick/httpproxy.rb
lib/webrick/httprequest.rb
lib/webrick/httpresponse.rb
lib/webrick/httpserver.rb
lib/webrick/httpservlet/abstract.rb
lib/webrick/httpservlet/filehandler.rb
lib/webrick/httputils.rb
lib/webrick/server.rb
test/webrick/test_filehandler.rb
test/webrick/test_httpserver.rb

Because Ruby 3.4 changed.
See https://bugs.ruby-lang.org/issues/16495

Change backquote to singlequote in messages
